name: Cuts Compiler CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
        matrix:
          destination:
            - "platform=macOS"
            - "platform=iOS Simulator,name=iPhone 16"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "sion-codin/cuts-app"
          token: "${{ secrets.TOKEN_GITHUB }}"

      - name: Build Cuts Compiler
        run: set -o pipefail && xcodebuild -scheme CutsCompiler -destination "${{ matrix.destination }}" | xcbeautify

