name: Cuts App CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      matrix:
        destination:
          - "platform=iOS Simulator,name=iPhone 16"
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "sion-codin/cuts-app"
          token: "${{ secrets.TOKEN_GITHUB }}"

      - name: Build Cuts App
        run: set -o pipefail && xcodebuild -scheme Cuts -configuration Debug -destination "${{ matrix.destination }}" test | xcbeautify