name: Demo Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Demo Step
        run: |
          echo "Running demo workflow in ${{ github.event.inputs.environment }} environment"
          echo "This workflow was synced from cuts-app repository"
          
      - name: Success
        run: echo "Demo workflow completed successfully!"
